repository:
  name: nixos-config
  description: my NixOs config
  topics: nix, nixos, dotfiles, devops, home manager

  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true

  default_branch: main
  delete_branch_on_merge: true
